Reduce two samples
neutrons/reflectivity_ui pull request #91
Opened 2024-06-03 15:17 UTC by backmari

# Short description of the changes:

# Long description of the changes:

# Check list for the pull request
- [ ] I have read the [CONTRIBUTING]
- [ ] I have read the [CODE_OF_CONDUCT]
- [ ] I have added tests for my changes
- [ ] I have updated the documentation accordingly

# Check list for the reviewer
- [ ] I have read the [CONTRIBUTING]
- [ ] I have verified the proposed changes
- [ ] best software practices
    + [ ] all internal functions have an underbar, as is python standard
    + [ ] clearly named variables (better to be verbose in variable names)
    + [ ] code comments explaining the intent of code blocks
- [ ] All the tests are passing
- [ ] The documentation is up to date
- [ ] code comments added when explaining intent

# Manual test for the reviewer

# References

2024-10-28 20:42 UTC, jmborr commented on reflectivity_ui/interfaces/data_handling/data_set.py
> +            String to add to reflectivity workspace name
can you include a usage example (for instance, what would `ws_suffix` be when dealing with multiple ROI's)

2024-10-29 15:01 UTC, jmborr requested changes

2024-10-29 16:53 UTC, backmari commented on reflectivity_ui/interfaces/data_manager.py
> +    def is_nexus_data_compatible(self, nexus_data: NexusData, reduction_list: list):
I replaced the one remaining usage of `is_active_data_compatible` with `is_nexus_data_compatible`

2024-10-29 17:15 UTC, backmari commented on reflectivity_ui/interfaces/event_handlers/main_handler.py
> +        if self.ui.tabWidget.currentIndex == self.DIRECT_BEAM_TAB_INDEX:
I found that `get_active_reduction_table` is redundant

2024-10-29 18:54 UTC, jmborr approved these changes

2024-10-29 19:03 UTC, merged